gPin/config/routes.rb
Rails.application.routes.draw do
  root 'pins#index'
  get '/pins', to: 'pins#index'
  get '/pins/new', to: 'pins#new'
  post '/pins', to: 'pins#create'
  get '/pins/:id', to: 'pins#show', as: :pin
  get '/pins/:id/edit', to: 'pins#edit', as: :edit_pin
  patch '/pins/:id', to: 'pins#update'
  put '/pins/:id', to: 'pins#update'
  delete '/pins/:id', to: 'pins#destroy'
  delete '/pins', to: 'pins#destroyAll'

end

gPin/app/models/pin.rb
class Pin < ActiveRecord::Base
	validates_presence_of :pinName
	validates_presence_of :url
	validates_presence_of :comment
	
end

gPin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

gPin/app/controllers/pins_controller.rb
class PinsController < ApplicationController

	def index
		@pins = Pin.all
		render :index
	end

	def new
		@pin = Pin.new
	end

	def create 
		@pin = Pin.new(pin_params)
		@pin.save #this line unnecessary
		if @pin.save
			redirect_to pins_path, flash: {success: "Successfully Created New Pin"}
		else
			#show me new page again
			render :new
			#show with error message
		end
	end

	def show
		@pin = Pin.find_by_id params[:id]
	end 

	def edit
		@pin = Pin.find_by_id params[:id]
	end

	def update
		@pin = Pin.find_by_id params[:id]
		#this line unnecessary 
		@pin.update pin_params #could instead by @pin.save
		if @pin.update pin_params
			redirect_to pin_path(@pin), notice: "Successfully Updated Pin"
		else
			render :edit
		end
	end

	def destroy
		pin = Pin.find(params[:id])
		pin.destroy
		redirect_to pins_path, alert: "Deleted Pin"
	end

	def destroyAll
		@pins = Pin.all
		@pins.destroy
		redirect_to pins_path
	end
private
	def pin_params
		params.require(:pin).permit(:pinName, :url, :comment, :imageURL)
	end


end

gPin/app/helpers/application_helper.rb
module ApplicationHelper
end

gPin/app/helpers/pins_helper.rb
module PinsHelper
end

gPin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gPin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <link href='http://fonts.googleapis.com/css?family=Josefin+Sans:600|Lobster+Two:700' rel='stylesheet' type='text/css'>
</head>
<body>
	<div id="heading">
	g-Pinterest
			<ul id="nav">

				<li class="no-link"><%= link_to "HOME", pins_path %></li>
				<li class="no-link">  |  </li>
				<li class="no-link"><%= link_to "NEW PIN", pins_new_path%></li>

			</ul>

	</div>
<div>

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "notice" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "alert" %>
  <% else %>
    <%= content_tag :div, value, class: "success" %>
  <% end %>
<% end %>

<%= yield %>
</div>
</body>
</html>

gPin/app/views/pins/_form.html.erb
<% if @pin.errors.any? %>
	<% @pin.errors.full_messages.each do |error| %>
		<p style="color:red"><%=error %></p>
		<% end %>
<% end %>

<%= form_for @pin do |f| %>
		<%= f.label "Pin" %>
		<%= f.text_field :pinName, autofocus: true %><br/>
    <%= f.label "URL" %>
    <%= f.text_field :url%><br />
    <%= f.label "Comment" %>
		<%= f.text_field :comment %><br/>
    <%= f.label "Image Url" %>
    <%= f.text_field :imageURL%><br />
    <%= f.submit "Add Pin", :class => 'button' %>
<% end %>

gPin/app/views/pins/edit.html.erb
<h3>Edit Your Pin</h3>

<%= render "form" %>

gPin/app/views/pins/index.html.erb
<h1>Check out my pins</h1>
<% @pins.each do |pin| %>
<div class="pin">

	<p><img width="190px" src="<%= pin.imageURL %>"></p>
	
	<h4><%= pin.pinName %></h4>
	<p><a href="<%= pin.url %>"><button>Visit Pin's URL</button></a></p>
	<button class="showComments">Click for Comments</button>
		<div class="comments">
			<p><%= pin.comment %></p>
			<button class="hideComments">Hide Comments</button>
		</div>
	<p><a href="pins/<%= pin.id %>/"><button>More on this pin</button></a></p>

	</div>
	<% end %>
	

gPin/app/views/pins/new.html.erb
<h3>Add a Pin</h3>

<%= render "form" %>

gPin/app/views/pins/show.html.erb
<h3><%= @pin.pinName %></h3>


<p><img width="400px" src="<%= @pin.imageURL %>" alt="Pin Image"></p>
<p>My Comment: <%= @pin.comment %></p>
<p><a href="<%= @pin.url %>"><button>Visit URL</button></a>
<a href="/pins/<%= @pin.id %>/edit"><button>Edit this pin</button></a> 
<%= link_to 'Delete Pin',  @pin,  method: :delete, data: {confirm: "Are you sure you want to delete this pin?"}, :class => 'button'%></p>
<p><a href="/pins"><button>Back Home</button></a></p>